micronaut:
  application:
    name: tbRestMicronautMongodb
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
